# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day22', '0002_hosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='port',
            field=models.IntegerField(),
        ),
    ]
